### ISSUE TITLE
Telegram bot password?

### ISSUE THREAD

**Issue by Calimerorulez** [alcmoraes/gramarr#8]
Hi,

Not actually an issue, but how do I generate a password which I need for the bot for the config file? I only have the bot API/token, and a chat ID... I tried to find the answer in the Telegram API documentation, but no luck...

Can you help me?

**Comment by matt-ints** [comment]
These are custom passwords that you can use for your bot, I just put in whatever and when I used the /auth command I had to input the user or admin pass specified in the config.json

**Comment by Calimerorulez** [comment]
Thanks! That worked great :)
